# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="48eca1e1-31b4-480d-9065-e6e3a9ca1e58"

# Отправлять уведомление на почту maximrybetsky@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - maximrybetsky@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

